"""chat_messages table

Revision ID: 9fd38fc6714a
Revises: 867eb2efbf72
Create Date: 2026-05-01 12:09:21.591930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9fd38fc6714a'
down_revision: Union[str, None] = '867eb2efbf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'tool', name='chat_message_role'), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_app_created', 'chat_messages', ['application_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_messages_app_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    sa.Enum(name='chat_message_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
