"""settings.local_llm_api_key_enc

Revision ID: 6d81484ec385
Revises: 9fd38fc6714a
Create Date: 2026-05-01 20:29:24.096613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d81484ec385'
down_revision: Union[str, None] = '9fd38fc6714a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('local_llm_api_key_enc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'local_llm_api_key_enc')
    # ### end Alembic commands ###
