"""auxiliary models

Revision ID: 93723269c59c
Revises: dc1c533a0989
Create Date: 2026-04-29 18:15:24.960394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93723269c59c'
down_revision: Union[str, None] = 'dc1c533a0989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_llm_provider', sa.String(length=32), nullable=False),
    sa.Column('anthropic_api_key_enc', sa.String(), nullable=True),
    sa.Column('local_llm_url', sa.String(length=2048), nullable=True),
    sa.Column('model_overrides', sa.JSON(), nullable=False),
    sa.Column('google_oauth_tokens_enc', sa.String(), nullable=True),
    sa.Column('smtp_config_enc', sa.String(), nullable=True),
    sa.Column('recruiter_name', sa.String(length=255), nullable=True),
    sa.Column('recruiter_email', sa.String(length=255), nullable=True),
    sa.Column('monthly_llm_spend_cap_usd', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'calendar', name='notification_channel'), nullable=False),
    sa.Column('provider', sa.Enum('gmail', 'smtp', name='notification_provider'), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'failed', name='notification_status'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('event_logs')
    op.drop_table('settings')
    # ### end Alembic commands ###
